### PR TITLE
Dependancies fix

### LINKED ISSUE #13: What wrong my code?
```
var elixir = require('laravel-elixir');
require("laravel-elixir-webpack");
var webpackConf = require(__dirname + '/webpack.config.js');
/*
 |--------------------------------------------------------------------------
 | Elixir Asset Management
 |--------------------------------------------------------------------------
 |
 | Elixir provides a clean, fluent API for defining some basic Gulp tasks
 | for your Laravel application. By default, we are compiling the Sass
 | file for our application, as well as publishing vendor resources.
 |
 */
elixir(function(mix) {
  mix.webpack("index.js");
});
```

 i run in console gulp and see 

```
/home/kaflan/Documents/test/test-app/gulpfile.js:18
  mix.webpack("index.js");
      ^

TypeError: mix.webpack is not a function
    at /home/kaflan/Documents/test/test-app/gulpfile.js:18:7
    at Elixir (/home/kaflan/Documents/test/test-app/node_modules/laravel-elixir/index.js:3:5)
    at Object.<anonymous> (/home/kaflan/Documents/test/test-app/gulpfile.js:17:1)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Liftoff.handleArguments (/usr/lib/node_modules/gulp/bin/gulp.js:116:3)
```

### PR DESCRIPTION
**Pull request by izziaraffaele**
Fixes #13

### CODE REVIEW

**Comment by joecohens** [comment]
Thanks @izziaraffaele! Just to check, what version of node/npm are you using?

**Comment by stephanedemotte** [comment]
Need this fix :)

**Comment by stephanedemotte** [comment]
come one Joe @izziaraffaele rocks, merge it !

**Comment by joecohens** [comment]
Sorry for the late merge and thanks!

**Comment by stephanedemotte** [comment]
yeaaah !

**Comment by izziaraffaele** [comment]
Thanks @stephanedemotte, I just do my best :) BTW I made some changes in this branch https://github.com/izziaraffaele/laravel-elixir-webpack/tree/features which will improve the watch command using webpack watch feature instead of gulp/elixir. 

As soon as I find the time to clean it up I'll make a PR but maybe you want to have a look at it already since I know it will improve the workflow of everybody using this package

**Comment by joecohens** [comment]
Nice! When you have it done let me know ;)

**Pull request merged**
